### ISSUE TITLE
Zip configuration issue.

### ISSUE THREAD

**Issue by SimDala1980** [mklasen/zip-creation-github-action#1]
This is not actually an issue with the good working action, just a wanted addon to finally solve my inital task.

I have a structure of repoName/repoName that I want to add to this zip-file that the action creates.

I haven't found a working solution since I don't know how, and if it's a good approach, to change folders before and after the zip command,

I haven't seen a working way to solve this structure with the zip command alone either. I end up with a folder named repoName fist in the zipfile, but I want the files and subfolders there.

**Comment by mklasen** [comment]
Can you paste your configuration in here? You can use the `cd` commands in Github actions, but it might be better to customize the zip command, `-j` or `--junk-paths` might work for you, or `zip -r test.zip test/*`.

**Comment by SimDala1980** [comment]
I've tried a great amout of different configurations to solve this but I haven't reached the goal yet. The problem by doing zip -r test.zip test/* is that the folder test will be included in the created zip-file. I also saw other ideas to get rid of the folder but that option removed all subfolders in the whole zip-file, wich mixed up even more. My current solution seems to create the zip-file in the right manner, but the next step fails since i've changed the working-directory. I haven't found a way to reset the working-directory to the repo root. Do you know a way to do that?

name: Create release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Zip Folder
        working-directory: ./${{ github.event.repository.name }}
        run: zip -r ..\${{ github.event.repository.name }}.zip .
              
      - name: Release
        
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{env.working-directory}}/${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by SimDala1980** [comment]
A solution could be to save the created zip-file in the ./${{ github.event.repository.name } directory and upload it to the release from there.

I can update to this way of handle the issure and see how that works.

**Comment by mklasen** [comment]
Are you able to do something like: `cd test && zip -r test.zip . && mv test.zip ../ && cd ../`?

**Comment by SimDala1980** [comment]
I was trying something like that before to, but didn't find a good way to ensure that the action is working even if the folder in the project is missing. To be able to have the action to go outside the repo root isn't a good solution.

When I tried to create the zip-file in the subfolder, it didn't find the zip-file in the next step:
![image](https://user-images.githubusercontent.com/103251328/207051234-4836eb2c-7ffa-43ed-bc94-5fd9f2c4fbdd.png)

**Comment by mklasen** [comment]
Seems to work fine for me:
https://github.com/conference7/zip-creation-github-action-without-parent
https://github.com/conference7/zip-creation-github-action-without-parent/blob/master/.github/workflows/release-action.yml
https://github.com/conference7/zip-creation-github-action-without-parent/releases/tag/v5

**Comment by SimDala1980** [comment]
Yes, the cd test works if the test folder exists. But if the test doesn't exist, will the cd test not work and still the cd.. work so that you end up in wrong final level outside the repo?

I read about security issues using cd cause of this may fail.

**Comment by mklasen** [comment]
Okay - well, there's a lot of options around this, run a bash script that checks if the directory exists or just make sure that the directory does exist in your repo.

I'm gonna go ahead and close this issue as there is no clear end result/question,
